apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: mohammed2asif/project
        ports:
        - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: project
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: project
