pipeline {
    agent any
    tools {
        git 'Default'
        terraform 'Terraform'
    }

    stages {
        stage('Checkout SCM') {
            steps {
                cleanWs()
                git branch: 'main', credentialsId: 'Github', url: 'https://github.com/yagnasivasai/terraform.git'
                sh 'git clone https://github.com/yagnasivasai/terraform.git'
            }
        }

        stage('Resource Creation') {
            steps {
                 sh '''
                    echo $BUILD_NUMBER
                    cd task_8_terraform_integration
                    terraform init
                    terraform plan
                    terraform apply -auto-approve
                    terraform show
                '''
            }
        }
    }
}













